### ISSUE TITLE
the application is erroring out requiring a clear node in the source

### ISSUE THREAD

**Issue by rafiksamman1982** [CameronWills/FatAntelope#5] opened 2017-03-17 19:29 UTC
The application is erroring out requiring a clear node <clear \> in the source web.config in the connectionStrings section.

**Comment by CameronWills** [comment] 2017-03-17 22:39
I don't understand the bug. Cannot seem to replicate..

I've tried adding <clear /> in the connectionStrings node on the demo page (https://fatantelopetester.apphb.com/) and it appears to generate the correct output?

Are you able to provide an example web configs (source and target)?
Obviously remove any private and sensitive information from the configs first..

Thanks,
Cameron

**Comment by rafiksamman1982** [comment] 2017-03-17 23:32
[File removed]

FatAntelope.exe SampleWeb.config Web.Config webxdt.config finalweb.config is the call i made.

**Comment by rafiksamman1982** [comment] 2017-03-17 23:34
I had to put a <clear \> in the SampleWeb.config to get it to work.

**Comment by rafiksamman1982** [comment] 2017-03-20 17:34
Hi Camerone, sorry to be a pest, is there any outlook on this?

**Comment by CameronWills** [comment] 2017-03-20 21:28
Hi Rafik,

I've pushed a fix in the latest version: https://github.com/CameronWills/FatAntelope/releases/tag/0.2.10

I'll close this issue now, be feel free to reopen if still experiencing problems.

**Closed as completed by CameronWills** 2017-03-20 21:28 UTC
Labels: bug

**Comment by rafiksamman1982** [comment] 2017-03-20 22:16
I have a question, is everything in the target file always preserved?

**Comment by CameronWills** [comment] 2017-03-21 02:37
Yes. That is the intention..
Applying the 'patch' file to the 'source' file should generate the same/equivalent XML as the 'target' file. **With the one exception**: nodes in the transformed file can appear in a different order to the target file.

Are you seeing some nodes not being preserved?

**Comment by rafiksamman1982** [comment] 2017-03-21 02:47
Not exactly, if you look at the target file at the bottom the basic http
binding does not match the source. but the changes in the source for that
basic http binding is not being transfered over is that supposed to happen?

**Comment by CameronWills** [comment] 2017-03-21 05:49
The purpose of the tool is to generate a patch, which is then used to convert 'source' into 'target'.

In your example, if there are XML nodes that exist in SampleWeb.config but don't exist in Web.config - they will be removed when the webxdt.config is applied.

Once the webxdt.config is applied to SampleWeb.config, the `<basicHttpBinding>` section` is the same as it appears in the 'Web.config'. **Assuming you're using the new version 0.2.10 to generate the patch**

Does that make sense?

**Comment by rafiksamman1982** [comment] 2017-03-21 14:56
That makes sense but the file set I gave you doesn't show that behavior the
node was updated but not all child elements were transfered.

**Comment by CameronWills** [comment] 2017-03-23 02:04
Yep, the bugs in 0.2.9 were affecting the that `<basicHttpBinding>` node as well.

**Comment by rafiksamman1982** [comment] 2017-03-23 14:42
Are you aware that the licensing terms of FatAntelope are commonly referred
to as a licensing virus by some?
I'm not able to you use this tool as a result of this.
Which license is this from? Or is this the original programmer's terms?

**Comment by rafiksamman1982** [comment] 2017-03-24 01:07
I need to know if i need to make the code that will call the FatAntelope.exe freely available to the public or if I can just refer back to this site and the original algorithm implementation's site.

**Comment by rafiksamman1982** [comment] 2017-03-24 14:22
Cameron sorry once again for pestering you but do you have an answer for two comments above?

**Comment by CameronWills** [comment] 2017-03-24 21:07
The license terms and conditions were from the original developer of the X-Diff algorithm and source code, which I ported from Java to C#. The X-Diff algorithm handles the comparison of XML documents.

From what I understand of condition 3 of their license, the source code of any binary that uses X-Diff, or it's derivatives, must be freely available and reproduce the license copyright and conditions..

So I think this would prohibit using FatAntelope being used in a closed-source or commercial product.

May I ask what you're building?

**Comment by rafiksamman1982** [comment] 2017-03-25 04:47
I'm responsible for our product updater utility. I'm trying to get the
web.config updates stabilized and I need a way to do that consitently
across all our webapps. The updater will call out to the FatAntelope.exe
from your release. Since it's just a command line interface call through a
process start in .net does that constitute a simple call through the os?
I'm not affecting the access to your code or the original programmer's
Algorithmic implementation. The updater is not a commercial tool it has
proprietary processes in there that affect our products but your tool is
the best at what I need it for right now and i'm in a bind not being able
to use it. Can a license be purchased?

**Comment by CameronWills** [comment] 2017-03-25 13:16
Ok, from my understanding of the license, the conditions relate to **redistribution** of X-Diff derivatives. 
So you're ok to use the FatAntelope privately within your organisation - as long as you're not redistributing software containing the X-Diff algorithm to third parties, or particularly if you're trying to commercially sell a piece of software that contains it.

From what you describe, you're using FatAntelope as part of your build / deployment process for your web apps? But the webapps themselves do not contain or use it ?

In this scenario, most people would use FatAntelope one time only, generate the patch file (web.release.config), and then include it webapp project (.csproj) underneath web.config. Then your developers would maintain this file going forward, alongside the web.config:

![image](https://cloud.githubusercontent.com/assets/1278887/24322489/513f4134-11b9-11e7-8a31-29d819b80e20.png)

But I might be mis-understanding your use.

**Comment by rafiksamman1982** [comment] 2017-03-25 13:20
We have an updater utility that is free that is distributed to customers so
they can receive updates in their environments. That utility needs fat
antelope to update customer web.configs in their environments. So I am
distributing my utility and fat antelope would be distributed.

**Comment by rafiksamman1982** [comment] 2017-03-27 16:47
Can I get a response on this? is a license available to be purchased?

**Comment by CameronWills** [comment] 2017-03-27 23:13
I'm not aware of a commercial license - you would need to contact the creator of X-Diff for their commercial licensing options..

Alternatively, you could offer the source code for your updater utility to your customers **if they asked for it?** If there is no risk to your business of loosing valuable intellectual property by sharing the source code? And then you would also just reproduce the copyright/license somewhere in the utility output?

**Comment by rafiksamman1982** [comment] 2017-03-27 23:21
We have security details regarding our products that we have in the updater
that we can't give the customers. Thanks for the reply, FatAntelope is
governed by very restrictive licensing terms as a result of the xdiff
algorithm port to c# and it actually does not provide one last feature that
I was looking for.

**Comment by CameronWills** [comment] 2017-03-28 01:14
No problem. Thanks for the feedback and sorry I cant be more helpful. I'm by no means a licensing guru, so feel free to get a second opinion. I chose X-Diff because it seemed like the simple implementation for unordered XML diffing.

What feature we're you referring to? Perhaps something worth implementing for the community?

**Comment by rafiksamman1982** [comment] 2017-03-28 01:27
The feature is to be able to provide parameters with actual xpaths and a
value for it for specific values that need to be updated after a merge is
one. Your utility can only be used in a private setting.

**Comment by rafiksamman1982** [comment] 2017-03-28 01:27
You can refer to xmlconfigmerge on code project
